spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pip-database.cb0ueqm04uwv.ap-northeast-2.rds.amazonaws.com:3306/pipdb
    username: admin
    password: 2024pip!

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
