name: Java CI with Gradle

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          package: 'jdk'
          jdk-version: '17.0.9'

      - name: checkout
        uses: actions/checkout@main

      - name: create env and secure file
        run: |
          touch .env
          echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Image build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose -f docker-compose-prod.yml build 
          docker push gyehwan/pip

      - name: Up docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # pem 키
          script: |
            set -e # 명령어 실행 중 오류 발생 시 스크립트 즉시 중단
            docker ps -qa | xargs -r docker stop
            docker ps -qa | xargs -r docker rm
            sudo docker rmi -f gyehwan/pip || true # 이미지가 없어도 오류를 무시하고 계속 진행
            sudo docker pull gyehwan/pip
            sudo cd
            sudo docker-compose -f docker-compose-prod.yml up -d
